### ISSUE TITLE
Version issues with stdlib

### ISSUE THREAD

**Issue by iversond** [psadmin-io/psadminio-io_weblogic#13]
The delivered version of `puppetlabs-stdlib` doesn't work with the `puppet-archive` module. When upgrading `puppetlabs-stdlib` to 4.19.0 (to use with `puppet-archive`) the DPK will return errors.

```
Error: Evaluation Error: Error while evaluating a Function Call, undefined method `repeated_param' for 
#<Puppet::Functions::DispatcherBuilder:0x000000068dbd18> at 
c:/programdata/puppetlabs/puppet/etc/modules/io_weblogic/manifests/init.pp:19:25 on node
```

**Comment by iversond** [comment]
Should there be a recommended version for `puppetlabs-stdlib` that works with both `puppet-archive` and the delivered 8.55 DPK files/puppet version?

**Comment by ericbisme** [comment]
Looking back at my notes we found that to be related to the version of Ruby used by puppet 3.8. In our Puppetfile we have the version of puppet/archive pinned to 0.5.1. I will do the same for v1 of this module and the others.

**Comment by ericbisme** [comment]
We're using stdlib v4.12 currently. Looking at the metadata.json I already have archive pinned to 0.5.1.
8.55 & 8.56 both are being delivered with stdlib 4.5.1.

See if using 4.12 works for your tests and if so we can pin these modules to that. Hopefully for v2 with 8.56/puppet4 that requirement will go away.
